name: Deploy Python API to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B1B7F174317348DF9C9F3713435E9C38 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D8421EB11284B80817377C2CEECF9D4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_88B1DA8547CF4D118B634DCB345C7197 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: resume-job-recommendation-api
          slot-name: Production
          package: ./backend
          startup-command: >
            gunicorn
            --bind=0.0.0.0
            --timeout 600
            -k uvicorn.workers.UvicornWorker
            app.main:app
